name: run-tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        php: [ 8.1, 8.2 ]
        stability: [ prefer-lowest, prefer-stable ]
        include:
          # Laravel 10 configurations
          - php: 8.1
            laravel: 10.*
            testbench: ^8.8
            carbon: ^2.67.0
            pest: ^2.34.7
            collision: ^7.10.0
          - php: 8.2
            laravel: 10.*
            testbench: ^8.8
            carbon: ^2.67.0
            pest: ^2.34.7
            collision: ^7.10.0
          # Laravel 11 configurations (only PHP 8.2)
          - php: 8.2
            laravel: 11.*
            testbench: ^9.0.0
            carbon: ^2.72.2
            pest: ^2.34.7
            collision: ^8.1.1

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "nesbot/carbon:${{ matrix.carbon }}" "pestphp/pest:${{ matrix.pest }}" "nunomaduro/collision:${{ matrix.collision }}" --dev --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: List Installed Dependencies
        run: composer show -D

      - name: Execute tests
        run: vendor/bin/pest
